Message queue for waiting player
gacikjakub/BattleShips pull request #24
Opened 2018-07-17 15:04 UTC by gacikjakub

Generally there is mechanism which allow us to simple initialize game and safe transfer data to waiting player which keeps asking backend about opponent shot result.

2018-07-17 15:06 UTC, krzysieksr approved these changes

2018-07-17 15:08 UTC, gacikjakub commented
Build 42 Successful
Deployed under: message-queue-for-waiting-player.battleships.kuba005.nazwa.pl

2018-07-18 11:55 UTC, xKoem requested changes

2018-07-18 11:55 UTC, xKoem commented on backend/src/main/java/pl/krkteam/battleships/opponent_shot_result_keeping/ShotResultQueueHolder.java
> +    public ShotResultQueueHolder() {}
reordering.. Constructors first

2018-07-18 11:55 UTC, xKoem commented on backend/src/main/java/pl/krkteam/battleships/opponent_shot_result_keeping/ShotResultQueueHolder.java
> +            throw new NoSuchElementException("Given player does not belong to this holder");
Maybe add own exceptions

2018-07-18 11:55 UTC, xKoem commented on backend/src/main/test/java/pl/krkteam/battleships/common/domain/GameBoardHolderTest.java
> +    public void shouldThrowExceptionWhenGivenPlayerToAddGameBoardIsNull() {
shouldThrowException_whenGivenPlayerToAddGameBoardIsNull - could have

2018-07-18 11:59 UTC, xKoem approved these changes

2018-07-18 13:27 UTC, AdrianHarenczyk approved these changes
Mainly ok :)

2018-07-18 13:27 UTC, AdrianHarenczyk commented on backend/src/main/java/pl/krkteam/battleships/common/domain/GameBoardHolder.java
> +            throw new IllegalArgumentException("Player cannot be null");
Could be refactored to separate method. It is code duplication.

2018-07-18 15:47 UTC, merged